using uint8_t=unsigned char; using uint16_t=unsigned short; using uint32_t=unsigned int; using int32_t=int; using size_t=unsigned int;
extern "C" void* memset(void* d,int v,size_t n){auto* p=static_cast<uint8_t*>(d);for(size_t i=0;i<n;++i)p[i]=static_cast<uint8_t>(v);return d;}
extern "C" void* memcpy(void* d,const void* s,size_t n){auto* a=static_cast<uint8_t*>(d);const auto* b=static_cast<const uint8_t*>(s);for(size_t i=0;i<n;++i)a[i]=b[i];return d;}
extern "C" int memcmp(const void* a,const void* b,size_t n){const auto* x=static_cast<const uint8_t*>(a);const auto* y=static_cast<const uint8_t*>(b);for(size_t i=0;i<n;++i)if(x[i]!=y[i])return x[i]<y[i]?-1:1;return 0;}
size_t string_length(const char* t){size_t n=0;while(t&&t[n])++n;return n;} int string_compare(const char*a,const char*b){while(*a&&*a==*b){++a;++b;}return static_cast<uint8_t>(*a)-static_cast<uint8_t>(*b);} bool string_equal(const char*a,const char*b){return string_compare(a,b)==0;} bool string_starts_with(const char*t,const char*p){while(*p)if(*t++!=*p++)return false;return true;} void string_copy(char*d,const char*s,size_t c){if(!c)return;size_t i=0;while(s[i]&&i+1<c){d[i]=s[i];++i;}d[i]=0;} bool is_space(char c){return c==' '||c=='\t';} char ascii_lower(char c){return c>='A'&&c<='Z'?static_cast<char>(c+32):c;} void lower_in_place(char*t){while(*t){*t=ascii_lower(*t);++t;}}
namespace console{void put(char){}void write(const char*){}void line(const char*){}void warning(const char*){}void success(const char*){}void unsigned_dec(uint32_t){}}
namespace serial{void put(char){}void write(const char*){}void line(const char*){}}
namespace zenov_generated{constexpr uint32_t kShellLineCapacity=512U;}
namespace heap{uint8_t arena[160U*1024U];uint32_t cursor=0;void* allocate(uint32_t n,uint32_t a){cursor=(cursor+a-1U)&~(a-1U);if(cursor+n>sizeof(arena))return nullptr;void*r=arena+cursor;cursor+=n;return r;}}
namespace storage{constexpr uint8_t zfs_type_file=1,zfs_type_directory=2;struct FileInfo{uint32_t type,size,checksum;};uint32_t fnv1a(const uint8_t*,uint32_t){return 1;}bool bytes_equal(const char*a,const char*b,uint32_t n){return memcmp(a,b,n)==0;}bool bytes_equal(const uint8_t*a,const uint8_t*b,uint32_t n){return memcmp(a,b,n)==0;}bool ready(){return true;}uint32_t file_capacity(){return 65536U;}bool normalize_path(const char*,char out[48]){out[0]='/';out[1]=0;return true;}bool query(const char*,FileInfo&){return false;}bool make_directory(const char*){return true;}bool read_file(const char*,uint8_t*,uint32_t,uint32_t&){return false;}bool write_file(const char*,const uint8_t*,uint32_t,bool){return true;}bool remove(const char*){return true;}bool sync_metadata(){return true;}}
namespace process{uint8_t buffer[65536];uint8_t* application_buffer=buffer;void serial_u32(uint32_t){}bool run(char*){return true;}}
namespace security_guard{struct Sha256Context{uint8_t opaque[128];};void sha256_init(Sha256Context& c){memset(&c,0,sizeof(c));}void sha256_update(Sha256Context&,const uint8_t*,uint32_t){}void sha256_final(Sha256Context&,uint8_t out[32]){memset(out,0,32);}enum class Verdict:uint8_t{clean,trusted,untrusted,suspicious,infected,error};enum class AuditAction:uint8_t{boot,scan,execute,quarantine};struct ScanResult{Verdict verdict;char path[48];char signature[48];uint8_t digest[32];uint32_t size;bool executable;};void sha256(const uint8_t*,uint32_t,uint8_t out[32]){memset(out,0,32);}bool digest_equal(const uint8_t*a,const uint8_t*b){return memcmp(a,b,32)==0;}bool zex_valid(const uint8_t*,uint32_t){return true;}bool elf_valid(const uint8_t*,uint32_t){return true;}ScanResult scan_memory(const char*,const uint8_t*,uint32_t,bool=false){ScanResult r{};r.verdict=Verdict::clean;return r;}void record(AuditAction,const ScanResult&){} }
namespace zgdb{struct BigInteger{uint32_t limb[64];};void big_from_be(BigInteger&,const uint8_t[256]);void big_to_be(const BigInteger&,uint8_t[256]);int32_t big_compare(const BigInteger&,const BigInteger&);void big_exp_65537(BigInteger&,const BigInteger&,const BigInteger&);}
#include "../kernel/parts/package_format.inc"
#include "../kernel/parts/package_catalog.inc"
#include "../kernel/parts/package_manager.inc"
